### ISSUE TITLE
comment on .css fonts for ePub

### ISSUE THREAD

**Issue by ousia** [wsexport/tool#117]
@Tpt, just accidentally I discovered the following code in `main.css`

``` css
body { font-family: FreeSerif, Arial, serif; }

body {
	line-height: 1.2;
}
```

Would it be possible that `main.css` could contain this code? (I mean, that the typefaces `FreeSerif, Linux Libertine` appear whether fonts are embedded in the ePub file or not.)

``` css
body {
	font-family: FreeSerif, LinuxLibertine, Arial, serif; 
	line-height: 1.2;
}
```

This won’t hurt anyone and it might help when FreeSerif or LinuxLibertine typefaces are present on the system (but not on the ePub document).

I’m providing a pull request, in case you would be interested in this.
